### ISSUE TITLE
ColorOS开机后 桌面立即崩溃（附LOG）

### ISSUE THREAD

**Issue by Marukon** [Kr328/Riru-IFWEnhance#12]
[logcat.txt](https://github.com/Kr328/Riru-IFWEnhance/files/10032631/logcat.txt)

[相关jar文件1.zip](https://github.com/Kr328/Riru-IFWEnhance/files/10032643/jar.1.zip)
[相关jar文件2.zip](https://github.com/Kr328/Riru-IFWEnhance/files/10032645/jar.2.zip)
恳请大佬解决，谢谢。

**Comment by SGZHACD** [comment]
具体是什么样子的崩溃呢

**Comment by Marukon** [comment]
> 

桌面FC

**Comment by Marukon** [comment]
> 具体是什么样子的崩溃呢

桌面FC

**Comment by noahhhi** [comment]
一模一样的问题，一加也用coloros了

**Comment by Kr328** [comment]
试试这个 Debug 的构建


**Zygisk:** [riru-ifw-enhance-v20.zip](https://github.com/Kr328/Riru-IFWEnhance/files/10608133/riru-ifw-enhance-v20.zip)
**Riru:** [riru-ifw-enhance-v20.zip](https://github.com/Kr328/Riru-IFWEnhance/files/10608134/riru-ifw-enhance-v20.zip)

**Comment by noahhhi** [comment]
两个都是riru版本，有zygisk版本吗

Kr328 ***@***.***> 于 2023年2月4日周六 15:16写道：

**Comment by Kr328** [comment]
@noahhhi 

**Riru:** [riru-ifw-enhance-v21.zip](https://github.com/Kr328/Riru-IFWEnhance/files/10608638/riru-ifw-enhance-v21.zip)
**Zygisk:** [zygisk-ifw-enhance-v21.zip](https://github.com/Kr328/Riru-IFWEnhance/files/10608639/zygisk-ifw-enhance-v21.zip)

**Comment by noahhhi** [comment]
问题已解决

Kr328 ***@***.***> 于 2023年2月4日周六 20:38写道：

**Comment by Marukon** [comment]
已修复，谢谢kr328大佬
